image_type_tezi.bbclass: allow inexistence of machine specific overlays
Gracefully continue should there not (yet) be any machine specific
device tree overlays.

This avoids the following build failure:

ERROR: Logfile of failure stored in: /home/user/builds/oe-core_4.0/build
/tmp/work/apalis_imx8-tdx-linux/console-tdx-image/1.0-r0/temp
/log.do_image_bootfs.4117712
Log data follows:
| DEBUG: Executing python function tezi_deploy_bootfs_files
| DEBUG: Python function tezi_deploy_bootfs_files finished
| DEBUG: Executing python function set_image_size
| DEBUG: 168906.400000 = 129928 * 1.300000
| DEBUG: 168906.400000 = max(168906.400000, 65536)[168906.400000] + 0
| DEBUG: 168907.000000 = int(168906.400000)
| DEBUG: 168907 = aligned(168907)
| DEBUG: returning 168907
| DEBUG: Python function set_image_size finished
| DEBUG: Executing shell function do_image_bootfs
| ls: cannot access 'apalis-imx8_*.dtbo': No such file or directory
| WARNING: /home/user/builds/oe-core_4.0/build/tmp/work
/apalis_imx8-tdx-linux/console-tdx-image/1.0-r0/temp
/run.do_image_bootfs.4117712:1 exit 2 from
 'machine_dtbos=`cd $deploy_dt_dir && ls apalis-imx8_*.dtbo`'
| ERROR: Execution of '/home/user/builds/oe-core_4.0/build/tmp/work
/apalis_imx8-tdx-linux/console-tdx-image/1.0-r0/temp
/run.do_image_bootfs.4117712' failed with exit code 2:
| ls: cannot access 'apalis-imx8_*.dtbo': No such file or directory
| WARNING: /home/user/builds/oe-core_4.0/build/tmp/work
/apalis_imx8-tdx-linux/console-tdx-image/1.0-r0/temp
/run.do_image_bootfs.4117712:1 exit 2 from
 'machine_dtbos=`cd $deploy_dt_dir && ls apalis-imx8_*.dtbo`'
|
ERROR: Task (/home/user/builds/oe-core_4.0/build/../layers
/meta-toradex-demos/recipes-images/images/console-tdx-image.bb
:do_image_bootfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5813 tasks of which 5544 didn't need to
 be rerun and 1 failed.
NOTE: Writing buildhistory
NOTE: Writing buildhistory took: 15 seconds

Signed-off-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>
(cherry picked from commit 0b33be8fed56b44c8f0b648da20d0b6706d8e7d5)